# Note: you may want to update this file and deploy-tags.yml at once
name: Publish dev (Docker image of staging)
on:
  push:
    branches:
      - staging
jobs:
  push_server:
    name: Push learn-ocaml image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          always_pull: true
          add_git_labels: true
          labels: "org.opencontainers.image.version=staging"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pfitaxel/learn-ocaml
          tags: staging
  push_client:
    name: Push learn-ocaml-client image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          always_pull: true
          add_git_labels: true
          labels: "org.opencontainers.image.version=staging"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pfitaxel/learn-ocaml-client
          target: client
          tags: staging
